### ISSUE TITLE
Running Unit Tests

### ISSUE THREAD

**Issue by JohnFF** [civicrm/civicrm-buildkit-vagrant#12]
I'm encountering the following error when trying to run unit tests out of the box on this awesome vagrant.

vagrant@civi:/srv/www/d7-master/sites/all/modules/civicrm/tools/scripts$ phpunit
PHPUnit 4.3.5 by Sebastian Bergmann.
...
vagrant@civi:/srv/www/d7-master/sites/all/modules/civicrm/tools$ scripts/phpunit
bash: scripts/phpunit: Permission denied
vagrant@civi:/srv/www/d7-master/sites/all/modules/civicrm/tools$ sudo scripts/phpunit
sudo: scripts/phpunit: command not found

The following works fine however. Perhaps it could be added to the instructions?

vagrant@civi:/srv/www/d7-master/sites/all/modules/civicrm/tools/scripts$ phpunit /srv/www/d7-master/sites/all/modules/civicrm/tests/phpunit/HelloTest.php 

PHPUnit 4.3.5 by Sebastian Bergmann.
Configuration read from /srv/www/d7-master/sites/all/modules/civicrm/tools/scripts/phpunit.xml
.
Time: 144 ms, Memory: 3.00MB
OK (1 test, 1 assertion)

**Comment by mattwire** [comment]
Resolved by #13
