### ISSUE TITLE
Drush

### ISSUE THREAD

**Issue by JohnFF** [civicrm/civicrm-buildkit-vagrant#14]
Hi,

On the d7-master, drush wasn't installed. I resolved this by altering /srv/www/d7-master/sites/all/modules/civicrm/composer.json.

Under require, adding
    "drush/drush": "8.1.3"

And changing symfony finder to
    "symfony/finder": "~2.7",

However, I can't find where in this repo I can add these! Some won't want drush installed on a non-dev server, but on a dev server it's pretty standard.

**Comment by totten** [comment]
Hmm, `drush` should be available, but I wonder how you're accessing the CLI?

Generally, with `civicrm-buildkit`, the idea is that all the developer-y CLI tools like `drush` or `civix` are installed one time as part of buildkit -- not installed separately for each build or each repo. This allows you to have the same+full toolchain across all builds (e.g. `d7-master`, `d7-46`, `wp-master`, etal).  The arrangement usually requires setting the `PATH` once).

The code under `sites/all/modules/civicrm` (aka `civicrm-core.git`) is supposed to be only the core stuff.

I don't have copy of the vagrantbox running here right now, but I imagine you login somehow (`ssh` or `vagrant ssh`). Login and then:
- Figure out where buildkit's `bin` dir is located (e.g. `find / -name civi-download-tools` should find it). 
- The `bin` dir is supposed to be in `PATH` (e.g. `export PATH=$HOME/buildkit/bin:$PATH`)
- Check that the `.profile` or `.bashrc` loaded during login is properly configured. (For Debian-based systems, you might want to check `~/.profile`, `~/.bash*`, `/etc/profile`, `/etc/bash*`, and so on.)

**Comment by mattwire** [comment]
Please reopen if this is still an issue
