### ISSUE TITLE
vagrant up not working after vagrant suspend

### ISSUE THREAD

**Issue by Exlord** [civicrm/civicrm-buildkit-vagrant#17]
Hi, I am noobi with civicrm/vagrant.
This is my first install. I have a slow internet so before running the vagrant, i downloaded the ubuntu/trusty64 from vagrant atlas and and added it manually.
`vagrant box add ubuntu/trusty64 [filepath]`. it worked but it says version 0.
 I shot down vagrant with `vagrant suspend` then tried `vagrant up` but id did not recognized my already existing VM and tried to build new one and failed.
So i got my VM's UUID and replaced the value in `\.vagrant\machines\default\virtualbox\id` file.
didn't worked at first but then i manually shot down the VM (from saved status to power off).
Now when i do `vagrant up` i get this :

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

it keeps repeating `default: Warning: Authentication failure. Retrying...` and then gives timeout error.

I also added `v.gui = true` to `vagrantfile` so now i have VM screen that is asking for login 

```
Ubuntu 14.04.5 LTS civi tty1
civi login :
```

now if i run `vagrant up` while vm is already running i get this out put :

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 civi.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 civi.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 d7-46.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 d7-master.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 wp-46.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 wp-master.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 d8-46.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 d8-master.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 b-46.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.123.10 b-master.dev
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
SSH Authentication failed , this is cuased by public/private keypair not properly set on guest vm.
```

I read in some post that i need to `chmod 0600 ~/.ssh/authorized_keys` but first i need to get into the vm os.
I tried admin:admin, demo:demo, root:root no success.

So whats the user/password to get into the vm ?
and why did this happened? did i do something wrong?

**Comment by nganivet** [comment]
Exlord - I cannot support you in this very specific configuration. The Vagrant box works perfectly if yhou let it download the packages. They are only downloaded once a Vagrant then cache them on the local machine.
