### ISSUE TITLE
The apache2 configtest failed

### ISSUE THREAD

**Issue by victorlenerd** [civicrm/civicrm-buildkit-vagrant#18]
Initially I tried using the manual method to install the buildkit but I swiched to using the vagrant installation method. everything went well except at the last part were I ran

vagrant up

but I keep getting this set of error...

==> default:  \* The apache2 configtest failed.
==> default: Output of config test was:
==> default: (2)No such file or directory: AH02291: Cannot access directory '/home/vagrant/.amp/log/' for error log of vhost defined at /etc/apache2/conf-enabled/civi.dev.conf:3
==> default: AH00014: Configuration check failed
==> default: Action 'configtest' failed.
==> default: The Apache error log may have more information.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Please I need help with this>_

**Comment by valerycodes** [comment]
@sleekvick Power off your virtual machine using `vagrant halt` and then try reapply the provisioning scripts with `vagrant up --provision or vagrant provision`.

**Comment by saurabhbatra96** [comment]
@sleekvick not sure if you're still looking into it, `vagrant ssh` and `mkdir ~/.amp/log` fixes this error.

**Comment by jackrabbithanna** [comment]
Still needed to do this as of 7-4-2017

**Comment by JKingsnorth** [comment]
Yup, I had to do this just now as well.

**Comment by gobnat** [comment]
Still occurring February 2018

**Comment by JKingsnorth** [comment]
@mattwire Thanks for pushing the fix up - unfortunately I'm still getting that error though.

I think it's actually due to an issue earlier in the script though, because the .amp directory doesn't exist (which is why it can't create the directory).

The nodejs process fails with:
 Cannot find module 'node-gyp/bin/node-gyp'

**Comment by mattwire** [comment]
@JKingsnorth @gobnat Can you try again?  I think the issues were because the provisioning script was install the dist version of npm first.

**Comment by JKingsnorth** [comment]
@mattwire Wahoo, worked perfectly that time. vagrant upped successfully.

**Comment by tiotsop01** [comment]
@mattwire I am having thesame issue. @JKingsnorth did you do anything extra to get it working for you?

**Comment by mattwire** [comment]
Are you using the latest version?

A domingo, 29/04/2018, 11:55, tiotsop01 <notifications@github.com> escreveu:

**Comment by tiotsop01** [comment]
Yes, I just clone the repo today. Is there another repo for the latest release?

**Comment by tiotsop01** [comment]
Yes, I just clone the repo today. Is there another repo for the latest release?

**Comment by ashish0910** [comment]
still getting this problem @mattwire .
