### ISSUE TITLE
Permissions for phpunit

### ISSUE THREAD

**Issue by JKingsnorth** [civicrm/civicrm-buildkit-vagrant#2]
First, thanks for this amazing tool!

But ( ;] ) I'm having trouble running phpunit tests. It looks like the /tools/scripts/phpunit script is not executable, even though it's group is 'vagrant'?

I'm trying to run the equivalent of:

```
cd /path-to/civicrm/tools
scripts/phpunit AllTests
```

**Comment by JKingsnorth** [comment]
I think this is because the script is in the 'shared folder' on the host machine, so the permission can't be set to be executable.

**Comment by nganivet** [comment]
John - you should be able to set the executable permission on phpunit. I am on a Windows machine so it is kindda funky to do that, appreciate if you could do a PR on this. Thanks.

**Comment by JKingsnorth** [comment]
Hmn, I'm using a Windows host as well. Are you able to get the tests to run on the guest after using vagrant ssh?
(I've been trying to run the tests from the host instead, but running into a [different issue ](http://civicrm.stackexchange.com/questions/10814/command-failed-cv-phpboot-level-settings-when-trying-to-run-tests) ;] )

**Comment by nganivet** [comment]
John - then please just do a 'chmod +x phpunit' from the vagrant VM and 
you should be good to go.

------ Original Message ------

**Comment by totten** [comment]
(a) IIRC, there was something surprising about how vagrant handles executable permissions on shared volumes. For example, it has default permissions that apply across the entire volume. If you set different permissions on a file, then they'll work under-the-hood... but they won't look right with `ls -l` (This was in OSX a month ago.) So +1 @nganivet try `chmod +x phpunit` from inside the VM.

(b) You might try calling phpunit with a different command:

``` bash
# Normal/old
cd civicrm/tools
./scripts/phpunit CRM_Core_RegionTest

# Alternative #1
cd civicrm/tools
php ./scripts/phpunit CRM_Core_RegionTest

# Alternative #2
cd civicrm
env CIVICRM_UF=UnitTests phpunit4 tests/phpunit/CRM/Core/RegionTest.php
```

**Comment by JKingsnorth** [comment]
Yeh, I ran into the problem that @totten mentions yesterday. If I `chmod +x phpunit` then the file permissions looked unchanged with `ls -l`.

I thought I'd tried **alternative 1** but that does seem to work. Thanks @totten . Maybe the permission change works under the hood, as you suggest, but not when calling it directly.

 [This ticket](https://www.virtualbox.org/ticket/1776) looks related, but I haven't waded through it yet (though it boasts 'fixed').

**Comment by mattwire** [comment]
@JKingsnorth Is this still an issue?

**Comment by JKingsnorth** [comment]
It seems to be working now @mattwire !
