### ISSUE TITLE
Problems with NPM

### ISSUE THREAD

**Issue by jackrabbithanna** [civicrm/civicrm-buildkit-vagrant#25]
After installing this into Ubunto 17.04

I could reach 'civi.dev' in the browser, but not 'http://d7-master.dev/'

It appears civibuild didn't build the instance...

vagrant ssh

I try 'civibuild d7-46'

And I get:
npm WARN npm npm does not support Node.js v0.10.25
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/

/usr/local/lib/node_modules/npm/lib/install.js:298
        [this, (next) => { computeMetadata(this.idealTree); next() }],
                       ^
npm ERR! Unexpected token >

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-07-04T17_21_09_231Z-debug.log

**Comment by jackrabbithanna** [comment]
would this have anything to do with the version of npm installed on the host computer?  It shouldn't right?

**Comment by mattwire** [comment]
Does https://github.com/civicrm/civicrm-buildkit-vagrant/pull/23 fix it?

**Comment by mattwire** [comment]
@jackrabbithanna Should be fixed by #23 which is now merged?  Please can you confirm and close this issue?
