### ISSUE TITLE
.dev sites on google chrome

### ISSUE THREAD

**Issue by gobnat** [civicrm/civicrm-buildkit-vagrant#32]
This is a minor quality of life issue.

Since version 66 (Dec 2017) Chrome now force redirects all sites ending in the ```.dev``` domain to https even on the localhost. [see this write up on the issue](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/). 

This causes a server response error when trying to view the pre-generated sites on chrome (Other browsers work fine).

We can manually add/modify existing host setting but it if it is not too large a job it may be worth modifying the ```.dev``` to something else like ```.devel``` or ```.localhost``` in the default settings.

Again thank you so much for all the work on this project!

**Comment by michaelmcandrew** [comment]
Hey there, this should be filed on the upstream https://github.com/civicrm/civicrm-buildkit if you fancy creating an issue there?

**Comment by michaelmcandrew** [comment]
I did it for you and am closing this issue. Let me know if there is a reason to re-open.
