### ISSUE TITLE
Cannot connect to new install - .dev domain issue

### ISSUE THREAD

**Issue by chrisfromredfin** [civicrm/civicrm-buildkit-vagrant#33]
Chrome and Firefox have implemented HSTS on the now-Google-owned .dev TLD. Those browsers MUST connect securely to .dev domains; however, no security certificate is available, and even making a self-signed available - Firefox cannot provide a security exception in this case.

I think the TLD used needs to be changed to .test or .localhost or something.

**Comment by mattwire** [comment]
@chrisfromredfin Thanks, I think this is an upstream issue - see https://github.com/civicrm/civicrm-buildkit/issues/394

**Comment by xurizaemon** [comment]
Oh, I created a dupe of this issue over at #40. There's plenty of baked-in .dev in this project too, PR over on that issue now, but you're right that it needs addressing in the issue you link to also.
