### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by JohnFF** [civicrm/civicrm-buildkit-vagrant#35]
Hi,

As we're trying to get more people using PHP7, is it a good idea to upgrade this to PHP 7?

There doesn't seem to be an easy way to get manual upgrades working!

John

**Comment by mattwire** [comment]
Good idea.  Happy to review a PR if you submit one.

**Comment by JohnFF** [comment]
I looked at this, but couldn't figure it out. Could you have a shot? My vagrant box creation skills are not ninja.

**Comment by kcristiano** [comment]
https://github.com/civicrm/civicrm-buildkit-vagrant/pull/44

**Comment by JohnFF** [comment]
Closing - thanks @kcristiano
