### ISSUE TITLE
can't even find civi.dev with IE

### ISSUE THREAD

**Issue by agloa** [civicrm/civicrm-buildkit-vagrant#38]
I just finished my first vagrant up. I'm not able to browse to http://civi.dev with any browser. I can sort of understand why that happens with Chrome and FF, but why would I get a 404 with IE?

I can ping civi.dev with no trouble, but I could use some help browsing there. Does this mean my installation failed somehow?

**Comment by xurizaemon** [comment]
Don't know about IE, but see #40 for PR to switch to using .test domain.

**Comment by mattwire** [comment]
Fixed via #41
