### ISSUE TITLE
Invalid state

### ISSUE THREAD

**Issue by adixon** [civicrm/civicrm-buildkit-vagrant#5]
Following these instructions on Ubuntu 14.04.4 LTS, I get an error, the end of which looks like:

==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

I tried vagrant up again and it gave me the same error. I wonder if the new vagrant has an issue? I followed the instructions and used the latest (1.8.1) version.

**Comment by nganivet** [comment]
Alan - I wrote this during the Vail Sprint but am not maintaining this 
package. Would be great if you could investigate/fix/submit PR. Thanks.

------ Original Message ------

**Comment by adixon** [comment]
Ah, okay. I'll see if I can make it work with an earlier vagrant.
