### ISSUE TITLE
Improve Windows setup

### ISSUE THREAD

**Issue by barbarae** [civicrm/civicrm-buildkit-vagrant#6]
I attended CiviCon and hoped to use this project to set up a development environment for developing on Windows. This has taken quite a bit of support, so this ticket is to record specific issues we identified (and resolutions where we found them).

This was on a University network at CiviCon so it's possible some issues were environment specific. Provider was Virtualbox.
## dnsmasq

Provision would fail when `dnsmasq` restarted - dnsmasq would point /etc/resolv.conf to 127.0.0.1, and after this all DNS requests would fail, preventing provision tasks which required internet access. Workaround was to back up the initial /etc/resolv.conf, `dpkg -r dnsmasq` on the client, restore the default resolv.conf, and comment out the dnsmasq package in `provision.sh`
## initial permissions

After provision, some files in `~vagrant/` belonged to root rather than vagrant. Resolution was `sudo chown -R vagrant: ~vagrant`
## apache not configured to use amp / incomplete provision

Post-install, Apache was not configured to use AMP. The [First Vagrant Up](https://github.com/civicrm/civicrm-buildkit-vagrant#the-first-vagrant-up) section suggests the client would come up with http://d7-master.dev, but that showed Apache's default start page instead. This might have been a failed `provision.sh` run - wget had timed out fetching hub.tgz, but the final message was "Provisioning completed in 1200s". To resolve, `vagrant ssh` then run `sudo /vagrant/provision/provision.sh` again. This completed the provision but didn''t leave d7-master.dev working - we also had to manually create `/etc/apache2/conf-available/amp.conf` with the line below, then enable that config.

```
Include /home/vagrant/.amp/apache.d/*.conf
```

**Comment by mattwire** [comment]
Please reopen if this is still valid
